#include "cJSON.h"

#define ITEM_CAS 		"cas"
#define ITEM_CMD 		"cmd"
#define ITEM_TYPE 		"type"
#define ITEM_CARDNO 		"cardno"
#define ITEM_GETSCNO 		"GetSCNo"
#define ITEM_DESC_STATE 	"DscState"
#define ITEM_PIN_INDEX		"pinIndex"
#define ITEM_TEXT_SELECTOR 	"textSelector"
#define ITEM_SERVICE_INDEX 	"serviceIndex"

#define ITEM_ORDER_PIN		"orderPin"
#define ITEM_CHECK_PIN		"checkPin"
#define ITEM_PURSE 		"purse"
#define ITEM_COST		"cost"
#define ITEM_MULT		"mult"
#define ITEM_DIV		"div"
#define ITEM_LOCATION		"location"
#define ITEM_SIGN0		"sign0"
#define ITEM_SIGN1000		"sign1000"
#define ITEM_COUNT		"count"
#define ITEM_LEN		"len"
#define ITEM_TEXT		"text"
#define ITEM_EVENTID		"eventId"
#define ITEM_GETVERSION		"GetVersion"
#define ITEM_VERSION		"version"
#define ITEM_DATE		"date"
#define ITEM_TIME		"time"
#define ITEM_PIN		"pin"
#define ITEM_REASON		"reason"

#define MAX_JSON_LEN (1024)

