#include "cJSON.h"

#define ITEM_CAS		"cas"
#define ITEM_CMD		"cmd"
#define ITEM_TYPE		"type"
#define ITEM_CARDNO		"cardno"
#define ITEM_GETSCNO		"GetSCNo"
#define ITEM_DESC_STATE		"DscState"
#define ITEM_PIN_INDEX		"pinIndex"
#define ITEM_TEXT_SELECTOR	"textSelector"
#define ITEM_SERVICE_INDEX	"serviceIndex"

#define ITEM_PIN_STATE		"pinstate"
#define ITEM_CHANGE_PIN		"changePin"
#define ITEM_ORDER_PIN		"orderPin"
#define ITEM_CHECK_PIN		"checkPin"
#define ITEM_PURSE		"purse"
#define ITEM_COST		"cost"
#define ITEM_MULT		"mult"
#define ITEM_DIV		"div"
#define ITEM_LOCATION		"location"
#define ITEM_SIGN0		"sign0"
#define ITEM_SIGN1000		"sign1000"
#define ITEM_COUNT		"count"
#define ITEM_LEN		"len"
#define ITEM_TEXT		"text"
#define ITEM_EVENTID		"eventId"
#define ITEM_GETVERSION		"GetVersion"
#define ITEM_VERSION		"version"
#define ITEM_DATE		"date"
#define ITEM_TIME		"time"
#define ITEM_PIN		"pin"
#define ITEM_REASON		"reason"
#define ITEM_ERROR_CODE		"errcode"

#define ITEM_OLD_PIN		"oldPin"
#define ITEM_OLD_PIN_LEN	"oldPinLen"
#define ITEM_NEW_PIN		"newPin"
#define ITEM_NEW_PIN_LEN	"newPinLen"

#define ITEM_GET_PURSE		"GetPurse"
#define ITEM_NUMBER		"number"

#define ITEM_OSD_ATTR		"OsdAttr"
#define ITEM_OSD_CONTENT	"osdContent"
#define ITEM_OSD_MODE		"osdMode"
#define ITEM_OSD_X		"osdX"
#define ITEM_OSD_Y		"osdY"
#define ITEM_OSD_W		"osdW"
#define ITEM_OSD_H		"osdH"
#define ITEM_OSD_BG		"osdBackground"
#define ITEM_OSD_ALPHA		"osdAlpha"
#define ITEM_OSD_FG		"osdForeground"
#define ITEM_OSD_DISPLAY	"OsdDisplay"
#define ITEM_OSD_DISPLAY_MODE   "osdDisplayMode"
#define ITEM_OSD_DISPLAY_DURATION "osdDisplayDuration"

#define ITEM_WATERMARK		"Watermark"
#define ITEM_ON			"on"
#define ITEM_CONFIG		"config"
#define ITEM_STRENGTH		"strength"

#define ITEM_OUTPUT_CONTROL	"OutputControl"
#define ITEM_FLAG		"flag"
#define ITEM_ANALOG		"analog"
#define ITEM_CGMSA		"cgmsa"
#define ITEM_EMICCI		"emicci"

#define ITEM_SVP		"Svp"
#define ITEM_ADDR		"address"

#define ITEM_ARB		"ARB"
#define ITEM_TA2TA		"TA2TA"
#define ITEM_CLIENTID		"clientid"
#define ITEM_DATA		"data"

#define ITEM_SET_ALGO           "SetAlgo"
#define ITEM_ALGO               "algo"

#define ITEM_HDCP		"hdcp"

#define ITEM_SESSION_ID		"id"
#define ITEM_BOXID		"boxid"
#define ITEM_GETBOXID		"GetBoxID"

#define MAX_JSON_LEN (1024)

